# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ATRA
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Anglicans for Truth, Renewal and Accountability (ATRA) is an informal, grassroots group of
  clergy and laity in the Anglican Church of North America (ACNA) actively working together
  on concrete steps toward accountability, renewal, and a healthier culture within the ACNA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anglicanrenewal.org" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:month/:title
facebook_username: anglicanrenewal

header_pages:
  # - about.md
  # - resources.md
  - connect.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-tailwind

tailwind:
  config: tailwind.config.js
  input: _assets/css/tailwind.css
  output: _site/assets/css/main.css

collections:
  requests:
    output: false
    permalink: /:collection/:path

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
